version: '3.5'
services:
  rabobank-poa:
    build: ./
    restart: always
    ports:
      - "8080"
  nginx:
    image: nginx
    volumes:
      - ./certs/localhost.crt:/tmp/localhost.crt
      - ./certs/localhost.key:/tmp/localhost.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rabobank-poa

